#! /bin/sh

dir=`dirname $0`

$dir/../../tests/filter_stderr_basic                    |

# Anonymise addresses
$dir/../../tests/filter_addresses                       |

# Remove "endicheck, ..." line and the following copyright line.
sed "/^endicheck, wrong endianity detector/ , /./ d"

exit 0
