
Memory does not contain data of endianity Target
A check of block at 0x........ was requested.
The endianity is invalid at bytes 1 (size 3) in that block
The value was probably created at this point:
   at 0x........: source (origins.c:8)
   by 0x........: ???
   by 0x........: main (origins.c:13)
   at 0x........: main (origins.c:17)


ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
